apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u9fh3nryg-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:e43fc0179e29acd48949cb2a70cd31ec5dcd5003@sha256:c0c5a3c48c6003441e19a0c850ce0598c61aaad0e30341de8b539adadf4dfc5a
          name: container-image
